(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SELECT VERSION(); args=None
(0.001) SHOW FULL TABLES; args=None
(0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
Exception while resolving variable 'error_message' in template 'login/signin.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error_message] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fe87e150ed8>>, \'user\': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7fe88c152110>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fe87e0a7ad0>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fe88c146250>, u\'request\': <WSGIRequest: GET \'/\'>}, {}, {\'block\': <Block Node: content. Contents: [<TextNode: u\'\\n\\n\\n<div class="row" id="s\'>, <IfNode>, <TextNode: u\'\\n\\t\\t\\t\\t<form action="\'>, <django.template.defaulttags.URLNode object at 0x7fe87e09ce50>, <TextNode: u\'" method="post">\\n\\t\\t\\t\\t\\t\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fe87e09ced0>, <TextNode: u\'\\n\\t\\t\\t\\t\\t<!-- <label for="us\'>, <django.templatetags.static.StaticNode object at 0x7fe87e09cf90>, <TextNode: u\'"/>\\n\\t\\t\\t\\t\\t </div>\\n\\n\\t      \'>, <django.template.defaulttags.URLNode object at 0x7fe87e0a7090>, <TextNode: u\'">Forgot Password?<span c\'>, <django.template.defaulttags.URLNode object at 0x7fe87e0a7190>, <TextNode: u\'">Create New Account<span\'>]>}]'
Exception while resolving variable 'error_message' in template 'login/signin.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error_message] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fe87e084848>>, \'user\': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7fe87e09c690>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fe87e09c9d0>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fe87e09c6d0>, u\'request\': <WSGIRequest: GET \'/\'>}, {}, {\'block\': <Block Node: content. Contents: [<TextNode: u\'\\n\\n\\n<div class="row" id="s\'>, <IfNode>, <TextNode: u\'\\n\\t\\t\\t\\t<form action="\'>, <django.template.defaulttags.URLNode object at 0x7fe87e0b76d0>, <TextNode: u\'" method="post">\\n\\t\\t\\t\\t\\t\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fe87e0b7710>, <TextNode: u\'\\n\\t\\t\\t\\t\\t<!-- <label for="us\'>, <django.templatetags.static.StaticNode object at 0x7fe87e0b77d0>, <TextNode: u\'"/>\\n\\t\\t\\t\\t\\t </div>\\n\\n\\t      \'>, <django.template.defaulttags.URLNode object at 0x7fe87e0b7890>, <TextNode: u\'">Forgot Password?<span c\'>, <django.template.defaulttags.URLNode object at 0x7fe87e0b7950>, <TextNode: u\'">Create New Account<span\'>]>}]'
Exception while resolving variable 'error_message' in template 'login/signin.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error_message] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fe797979c80>>, \'user\': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7fe79d1d5f50>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fe7979948d0>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fe79d1d50d0>, u\'request\': <WSGIRequest: GET \'/\'>}, {}, {\'block\': <Block Node: content. Contents: [<TextNode: u\'\\n\\n\\n<div class="row" id="s\'>, <IfNode>, <TextNode: u\'\\n\\t\\t\\t\\t<form action="\'>, <django.template.defaulttags.URLNode object at 0x7fe797986c50>, <TextNode: u\'" method="post">\\n\\t\\t\\t\\t\\t\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fe797986cd0>, <TextNode: u\'\\n\\t\\t\\t\\t\\t<!-- <label for="us\'>, <django.templatetags.static.StaticNode object at 0x7fe797986d90>, <TextNode: u\'"/>\\n\\t\\t\\t\\t\\t </div>\\n\\n\\t      \'>, <django.template.defaulttags.URLNode object at 0x7fe797986e50>, <TextNode: u\'">Forgot Password?<span c\'>, <django.template.defaulttags.URLNode object at 0x7fe797986f50>, <TextNode: u\'">Create New Account<span\'>]>}]'
Exception while resolving variable 'error_message' in template 'login/signin.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error_message] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fe7979355f0>>, \'user\': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7fe797986490>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fe7979867d0>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fe7979864d0>, u\'request\': <WSGIRequest: GET \'/\'>}, {}, {\'block\': <Block Node: content. Contents: [<TextNode: u\'\\n\\n\\n<div class="row" id="s\'>, <IfNode>, <TextNode: u\'\\n\\t\\t\\t\\t<form action="\'>, <django.template.defaulttags.URLNode object at 0x7fe7979e1790>, <TextNode: u\'" method="post">\\n\\t\\t\\t\\t\\t\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fe7979e1310>, <TextNode: u\'\\n\\t\\t\\t\\t\\t<!-- <label for="us\'>, <django.templatetags.static.StaticNode object at 0x7fe7979e13d0>, <TextNode: u\'"/>\\n\\t\\t\\t\\t\\t </div>\\n\\n\\t      \'>, <django.template.defaulttags.URLNode object at 0x7fe7979e1510>, <TextNode: u\'">Forgot Password?<span c\'>, <django.template.defaulttags.URLNode object at 0x7fe7979e1650>, <TextNode: u\'">Create New Account<span\'>]>}]'
Exception while resolving variable 'error_message' in template 'login/signin.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error_message] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fe7979356e0>>, \'user\': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7fe7979789d0>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fe797978d50>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fe797978a10>, u\'request\': <WSGIRequest: GET \'/\'>}, {}, {\'block\': <Block Node: content. Contents: [<TextNode: u\'\\n\\n\\n<div class="row" id="s\'>, <IfNode>, <TextNode: u\'\\n\\t\\t\\t\\t<form action="\'>, <django.template.defaulttags.URLNode object at 0x7fe797934dd0>, <TextNode: u\'" method="post">\\n\\t\\t\\t\\t\\t\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fe797994cd0>, <TextNode: u\'\\n\\t\\t\\t\\t\\t<!-- <label for="us\'>, <django.templatetags.static.StaticNode object at 0x7fe797994c90>, <TextNode: u\'"/>\\n\\t\\t\\t\\t\\t </div>\\n\\n\\t      \'>, <django.template.defaulttags.URLNode object at 0x7fe797994f90>, <TextNode: u\'">Forgot Password?<span c\'>, <django.template.defaulttags.URLNode object at 0x7fe797994a50>, <TextNode: u\'">Create New Account<span\'>]>}]'
Exception while resolving variable 'error_message' in template 'login/signin.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error_message] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7f92fcf12c80>>, \'user\': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f92fe73bf50>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7f92fcf2e8d0>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f92fe73b0d0>, u\'request\': <WSGIRequest: GET \'/\'>}, {}, {\'block\': <Block Node: content. Contents: [<TextNode: u\'\\n\\n\\n<div class="row" id="s\'>, <IfNode>, <TextNode: u\'\\n\\t\\t\\t\\t<form action="\'>, <django.template.defaulttags.URLNode object at 0x7f92fcf1fc50>, <TextNode: u\'" method="post">\\n\\t\\t\\t\\t\\t\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7f92fcf1fcd0>, <TextNode: u\'\\n\\t\\t\\t\\t\\t<!-- <label for="us\'>, <django.templatetags.static.StaticNode object at 0x7f92fcf1fd90>, <TextNode: u\'"/>\\n\\t\\t\\t\\t\\t </div>\\n\\n\\t      \'>, <django.template.defaulttags.URLNode object at 0x7f92fcf1fe50>, <TextNode: u\'">Forgot Password?<span c\'>, <django.template.defaulttags.URLNode object at 0x7f92fcf1ff50>, <TextNode: u\'">Create New Account<span\'>]>}]'
